### ISSUE TITLE
Broken player's metadata after upgrade up to 1.13

### ISSUE THREAD

**Issue by DmitryRendov** [DmitryRendov/PhantomAdmin#5]
After upgrade to 1.13 there's a kick of OP players with an exception:
`[06:44:26] [Server thread/WARN]: Failed to handle packet for /10.0.2.2:59821
net.minecraft.server.v1_13_R1.ReportedException: Loading entity NBT
        at net.minecraft.server.v1_13_R1.Entity.f(Entity.java:1758) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.WorldNBTStorage.load(WorldNBTStorage.java:209) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.PlayerList.a(PlayerList.java:312) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.PlayerList.a(PlayerList.java:104) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:150) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:54) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at com.google.gson.internal.Streams.parse(Streams.java:60) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:493) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:518) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:286) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.Entity.f(Entity.java:1678) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        ... 12 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at com.google.gson.internal.Streams.parse(Streams.java:46) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:493) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:518) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:286) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.Entity.f(Entity.java:1678) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        ... 12 more
[06:44:26] [Server thread/INFO]: com.mojang.authlib.GameProfile@5d05625b[id=6167a377-f470-334b-97e3-25519d58eb1d,name=Demon,properties={textures=[com.mojang.authlib.properties.Property@404b691a]},legacy=false] (/10.0.2.2:59821) lost connection: Internal server error
`

**Comment by DmitryRendov** [comment]
the reason is changed customname format
![customname-issue](https://user-images.githubusercontent.com/1677593/44450080-ad229f80-a5f8-11e8-9858-c30724ac3b00.png)

Since it affects only OP users, fixed via NBTExprorer. 
I'm leaving the issue open for the future - there's a need to add migration part to the plugin.
