### ISSUE TITLE
Could not pass event EntityTargetLivingEntityEvent to PhantomAdmin v2.4.3

### ISSUE THREAD

**Issue by DmitryRendov** [DmitryRendov/PhantomAdmin#8]
`Could not pass event EntityTargetLivingEntityEvent to PhantomAdmin v2.4.3
java.lang.NullPointerException: null`

`[18:34:34] [Server thread/ERROR]: Could not pass event EntityTargetLivingEntityEvent to PhantomAdmin v2.4.3
java.lang.NullPointerException: null
        at me.ryanhamshire.PhantomAdmin.PAEventHandler.onEntityGotTarget(PAEventHandler.java:104) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-176]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityTargetLivingEvent(CraftEventFactory.java:1136) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.EntityExperienceOrb.tick(EntityExperienceOrb.java:134) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:431) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-176]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]`

**Comment by DmitryRendov** [comment]
resolved via #9
